/**
 * routes.tsx, the navigation model shared by the shell (App.tsx) and the
 * hash router. Exactly the 13 sidebar areas requested for the desktop skeleton
 * (doc 11 §2). Each entry maps a stable hash `id` to its label and page
 * component. UI authors fill the page components; they do NOT edit this file or
 * App.tsx, so the 4 module authors never collide.
 */
import type { ComponentType } from "react";
import Dashboard from "./Dashboard";
import Timer from "./Timer";
import Today from "./Today";
import Week from "./Week";
import Customers from "./Customers";
import Projects from "./Projects";
import Tasks from "./Tasks";
import Reports from "./Reports";
import Invoices from "./Invoices";
import Backdating from "./Backdating";
import Compliance from "./Compliance";
import Settings from "./Settings";
import Sync from "./Sync";

export interface RouteDef {
  /** Stable hash id, e.g. "dashboard" → `#/dashboard`. */
  id: string;
  /** Sidebar label (de). */
  label: string;
  /** The page component. */
  Component: ComponentType;
}

export const ROUTES: readonly RouteDef[] = [
  { id: "dashboard", label: "Dashboard", Component: Dashboard },
  { id: "timer", label: "Timer", Component: Timer },
  { id: "today", label: "Heute", Component: Today },
  { id: "week", label: "Woche", Component: Week },
  { id: "customers", label: "Kunden", Component: Customers },
  { id: "projects", label: "Projekte", Component: Projects },
  { id: "tasks", label: "Aufgaben", Component: Tasks },
  { id: "reports", label: "Reports", Component: Reports },
  { id: "invoices", label: "Rechnungen", Component: Invoices },
  { id: "backdating", label: "Nachträge", Component: Backdating },
  { id: "compliance", label: "Compliance", Component: Compliance },
  { id: "settings", label: "Einstellungen", Component: Settings },
  { id: "sync", label: "Sync", Component: Sync },
] as const;

/** Fallback route id when the hash is empty or unknown. */
export const DEFAULT_ROUTE = "dashboard";

/** Resolve a hash (`#/timer`) to a known route, or the default. */
export function resolveRoute(hash: string): RouteDef {
  const id = hash.replace(/^#\/?/, "").split("/")[0];
  // ROUTES is a non-empty literal; the `!` is safe and keeps the return type RouteDef.
  return ROUTES.find((r) => r.id === id) ?? ROUTES[0]!;
}
